Repository michal-hudy/mockice, pull requests merged in 2019-09, with the labels that each got.

#3 Add methods descriptions
  README.md
  pkg/endpoint/endpoint.go
  pkg/endpoint/endpoint_test.go
  pkg/service/service.go
Labels: enhancement

#4 Add shields to readme
  .github/workflows/build.yml
  .github/workflows/pre.yml
  README.md
Labels: documentation, enhancement

#5 Update readme file
  README.md
Labels: documentation, enhancement

#6 Language review of the README.md
  README.md
Labels: documentation, enhancement

#7 Add unit test to business logic
  .github/workflows/build.yml
  .github/workflows/pre.yml
  README.md
  go.mod
  go.sum
  main.go
  pkg/endpoint/endpoint.go
  pkg/endpoint/endpoint_test.go
  pkg/log/log_test.go
  pkg/service/service.go
  pkg/service/service_test.go
  pkg/signal/signal.go
  pkg/signal/signal_test.go
Labels: enhancement

#8 Add Goreleaser configuration
  .gitignore
  .goreleaser.yml
Labels: enhancement

#9 Fix configuration parsing
  .goreleaser.yml
  pkg/endpoint/endpoint.go
Labels: bug

#11 Add support for files
  README.md
  pkg/endpoint/endpoint.go
  pkg/endpoint/endpoint_test.go
  pkg/endpoint/testdata/test.md
Labels: documentation, enhancement
